<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="5" hostname="SWQA-NV-LEN" failures="1" tests="2" name="Test" time="26.198" errors="0" timestamp="2025-09-13T14:47:55 PDT">
  <testcase classname="com.qa.tests.LoginTests" name="invalidPassword" time="4.084">
    <failure type="java.lang.AssertionError" message="expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.sdsd]">
      <![CDATA[java.lang.AssertionError: expected [Username and password do not match any user in this service.] but found [Username and password do not match any user in this service.sdsd]
at com.qa.tests.LoginTests.invalidPassword(LoginTests.java:82)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1604)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- invalidPassword -->
  <testcase classname="com.qa.tests.ProductTests" name="validateProductOnProductsDetailPage" time="8.967"/>
  <testcase classname="com.qa.BaseTest" name="@AfterTest afterTest" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterTest afterTest -->
  <testcase classname="com.qa.tests.ProductTests" name="validateProductOnProductsPage" time="0.0">
    <ignored/>
  </testcase> <!-- validateProductOnProductsPage -->
  <testcase classname="com.qa.BaseTest" name="@BeforeTest beforeTest" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeTest beforeTest -->
  <testcase classname="com.qa.tests.LoginTests" name="invalidUserNameTest" time="0.0">
    <ignored/>
  </testcase> <!-- invalidUserNameTest -->
  <testcase classname="com.qa.tests.LoginTests" name="successfulLogin" time="0.0">
    <ignored/>
  </testcase> <!-- successfulLogin -->
</testsuite> <!-- Test -->
